# Site settings
title: Christopher's Portfolio
description: Come see what sklls Chris has to offer
baseurl: "/home" # the subpath of your site, e.g. /blog
url: "https://idecay.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Christopher Greenwood
user_description: I am a USMC veteran who is looking to enter a career that doesn't just pay the bills but ignites my passion as well. Software development allows me to utilize my talents as a tenacious problem solver to bring the skills and determination necessary to conquer any challenge.
user_title: Software Developer
email: greenwood.cm88@gmail.com
twitter_username: lorem_ipsum
github_username: idecay
gplus_username: lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ["package.json", "src", "node_modules"]
